### ISSUE TITLE
Pressing enter on user result 

### ISSUE THREAD

**Issue by jjw24** [Garulf/Github-Quick-Launcher#10]
It seems pressing enter on user result from e.g. `@Garulf` does not do anything (opening via context menu works).

Am on the latest plugin version.

**Comment by Garulf** [comment]
I think your message got cut off. Could you please resend?

**Comment by Garulf** [comment]
> It seems pressing enter on user result from e.g. `@Garulf` does not do anything (opening via context menu works).
> 
> 
> 
> Am on the latest plugin version.

I'll take a look.

**Comment by jjw24** [comment]
This is working. Not sure what happened there.
