### ISSUE TITLE
Not showing private repos from user or organization

### ISSUE THREAD

**Issue by backmind** [Garulf/Github-Quick-Launcher#17]
Hey, thanks for the plugin

I am not able to set it properly to list all the repos, including private ones (from my own user or from org I am part of). I think I set the personal Access Token properly (check the image), but actually none of them are shown.
![image](https://user-images.githubusercontent.com/60194650/216122596-b68aacbb-49c2-43a8-829f-8c0a48f293ad.png)

Best!

**Comment by Garulf** [comment]
Should be fixed in 3.0.0 release!
