### ISSUE TITLE
Result when user's repo contains substring of intended repo 

### ISSUE THREAD

**Issue by jjw24** [Garulf/Github-Quick-Launcher#4]
Hey, I set my username in the settings, when I search Flow.Launcher it gave me my own repo  but my intended repo is the flow's actual repo.

![image](https://user-images.githubusercontent.com/26427004/150432419-8f52cedf-4f2a-4b1a-9aba-6eb67c185bba.png)

**Comment by Garulf** [comment]
You can resolve this by typing the org/username before the repo like so: `Flow-Launcher/Flow.Launcher`.

I intend to add a keyword/symbol to force the plugin to search Non-owned repos when a match is found in your own repo list.

**Comment by Garulf** [comment]
You can now search for repos by starting your query with a `/`. 

Example: `/Flow-Launcher`

**Comment by jjw24** [comment]
Love it, thank you.

**Comment by Garulf** [comment]
Just found out if you include `org:read` access with your token it will also bring up your Org repositories.

https://github.com/Garulf/Github-Quick-Launcher/blob/main/README.md#personal-access-token
