### ISSUE TITLE
Search username without token

### ISSUE THREAD

**Issue by jjw24** [Garulf/Github-Quick-Launcher#7]
Is it possible to search for username without the token?

**Comment by Garulf** [comment]
You should be able to do this already.

Are you talking about this?
![image](https://user-images.githubusercontent.com/535299/150701448-3532d667-6fec-4853-ba2c-96fd46bf8a5f.png)

**Comment by jjw24** [comment]
hmm this searches the users and their repos at the same time, I was more looking for just searching the user and opening up which leads to the user's home page.

**Comment by Garulf** [comment]
> hmm this searches the users and their repos at the same time, I was more looking for just searching the user and opening up which leads to the user's home page.

Something like this?

![image](https://user-images.githubusercontent.com/535299/150879907-0a20d71e-c8e3-4b9a-9a68-15807431a62e.png)

And maybe a context option to open users homepage?

**Comment by jjw24** [comment]
Yeah that will be good. I thought when selecting the result would open the user's profile page? Does it need anything in context menu?

**Comment by Garulf** [comment]
The dev code I have inserts the selected username into the plugin like so: `gr Garulf/` when selected. 

You’re saying it might be best to have the result take you directly to the users page in browser?

**Comment by jjw24** [comment]
Oh ok i didnt know it does that, im ok with a context menu then. Does having `gr Garulf/` allow me then to search for the repos  in the user?

I am on 1.2.2 and selecting the user result doesnt open up anything.

**Comment by Garulf** [comment]
`gr Garulf/` Will search all Garulf's public repos. 

`gr @Garulf` will search for any user with the name "Garulf".
Selecting the result will changequery to `gr garulf/`. Opening context on a user when using the `@` keyword will allow you to open that user's Github page.

**Comment by jjw24** [comment]
yep sounds good

**Comment by Garulf** [comment]
> yep sounds good

Oh and you'll want to update to 1.3.0
